### ISSUE TITLE
Search all products from My Library

### ISSUE THREAD

**Issue by phallalay** [161io/labodata-api#1]
Dear Benoit Asselin,

I am developing a shop website by Woocommerce WordPress, I would like to know if I can search for all products from my own Labodata Library using the current API. 
Thank you.

Phalla

**Comment by basselin** [comment]
Dear Phalla,

You can use `search.json` with the key `purchase=1` to search in your library.

Benoit

**Comment by phallalay** [comment]
> Dear Phalla,
> 
> You can use `search.json` with the key `purchase=1` to search in your library.
> 
> Benoit

Dear Benoit,

Thank you for your response, I will try this key if that works as expected.

Thank you,
Phalla

**Comment by phallalay** [comment]
Dear Benoit,

That solved my problem. 

Thank you
