### ISSUE TITLE
Search for only private product

### ISSUE THREAD

**Issue by phallalay** [161io/labodata-api#2]
Dear Benoit,

I am looking for the search product from my own library and private product only
https://www.labodata.com/api/v1/product/search.json
I used purchase=1 & private=1 but the result return with all items from my library
Is there anything I have to do?

Thank you

**Comment by basselin** [comment]
Dear Phalla,

`private=1` is not available. We will try to add it quickly.

Benoit

**Comment by phallalay** [comment]
Dear Benoit,

Thank you in advance for adding this.

Best,
Phalla

**Comment by basselin** [comment]
`private=1` is available !
You can use it without `purchase=1`.

Benoit

**Comment by phallalay** [comment]
Dear Benoit,

I really appreciate your update.

Thank you
Phalla
